version: "3.7"
services:
    web:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./webhole:/www
            - ./conf.d:/etc/nginx/conf.d

    php:
        image: php:fpm
        volumes:
            - ./webhole:/www
