version: "3.7"
services:
    web:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./webhole:/www
            - ./conf.d:/etc/nginx/conf.d

    php:
        build: ./php
        volumes:
            - ./webhole:/www

    db:
        image: mariadb
        ports:
         - "3306:3306"
        volumes:
         - data:/var/lib/mysql
         - ./db/data-dump.sql:/docker-entrypoint-initdb.d/dump.sql

        environment:
            MYSQL_ROOT_PASSWORD: root

            

volumes:
  data:    

