<div class="p-3 mb-2 bg-secondary text-white"></div><h1 class="text-center">Assistance Support</h1></div>

<div class="alert alert-primary" role="alert">


<div class="p-3 mb-2 bg-secondary text-white"></div><h1 class="text-center">Assistance Support</h1></div>

<div class="alert alert-primary" role="alert">
        
 <div class="container">
                <!-- Content here -->
                   
            <div class="form-group">
                <label for="exampleFormControlInput1">Email address</label>
                <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
            </div>


            <div class="form-group">
                <label for="exampleFormControlSelect1">Selectionnez un sujet dans la liste ci-dessous :</label>
                <select class="form-control" id="exampleFormControlSelect1">
                <option><p class="text-center">Problème de connexion</p></option>
                <option><p class="text-center">Perte de mot de passe</p></option>
                <option><p class="text-center">Autre</p></option>
                </select>
            </div>


    
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Message</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
    


            <form>
                    <div class="form-group">
                        <label for="exampleFormControlFile1">Charger un fichier</label>
                        <input type="file" class="form-control-file" id="exampleFormControlFile1">
                    </div>

    
                    <button type="button" class="btn btn-primary">Valider</button> 

            </form>
 </div>
        
</div>